//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Wrapper.Dao
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class global_dataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new global_dataEntities object using the connection string found in the 'global_dataEntities' section of the application configuration file.
        /// </summary>
        public global_dataEntities() : base("name=global_dataEntities", "global_dataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new global_dataEntities object.
        /// </summary>
        public global_dataEntities(string connectionString) : base(connectionString, "global_dataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new global_dataEntities object.
        /// </summary>
        public global_dataEntities(EntityConnection connection) : base(connection, "global_dataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<hotelcomment> hotelcomment
        {
            get
            {
                if ((_hotelcomment == null))
                {
                    _hotelcomment = base.CreateObjectSet<hotelcomment>("hotelcomment");
                }
                return _hotelcomment;
            }
        }
        private ObjectSet<hotelcomment> _hotelcomment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<hotelinfo> hotelinfo
        {
            get
            {
                if ((_hotelinfo == null))
                {
                    _hotelinfo = base.CreateObjectSet<hotelinfo>("hotelinfo");
                }
                return _hotelinfo;
            }
        }
        private ObjectSet<hotelinfo> _hotelinfo;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the hotelcomment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohotelcomment(hotelcomment hotelcomment)
        {
            base.AddObject("hotelcomment", hotelcomment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the hotelinfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohotelinfo(hotelinfo hotelinfo)
        {
            base.AddObject("hotelinfo", hotelinfo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="global_dataModel", Name="hotelcomment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class hotelcomment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new hotelcomment object.
        /// </summary>
        /// <param name="idHotelComment">Initial value of the idHotelComment property.</param>
        /// <param name="hotelid">Initial value of the Hotelid property.</param>
        /// <param name="pageCount">Initial value of the PageCount property.</param>
        public static hotelcomment Createhotelcomment(global::System.Int32 idHotelComment, global::System.Int32 hotelid, global::System.Int32 pageCount)
        {
            hotelcomment hotelcomment = new hotelcomment();
            hotelcomment.idHotelComment = idHotelComment;
            hotelcomment.Hotelid = hotelid;
            hotelcomment.PageCount = pageCount;
            return hotelcomment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idHotelComment
        {
            get
            {
                return _idHotelComment;
            }
            set
            {
                if (_idHotelComment != value)
                {
                    OnidHotelCommentChanging(value);
                    ReportPropertyChanging("idHotelComment");
                    _idHotelComment = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idHotelComment");
                    OnidHotelCommentChanged();
                }
            }
        }
        private global::System.Int32 _idHotelComment;
        partial void OnidHotelCommentChanging(global::System.Int32 value);
        partial void OnidHotelCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Hotelid
        {
            get
            {
                return _Hotelid;
            }
            set
            {
                OnHotelidChanging(value);
                ReportPropertyChanging("Hotelid");
                _Hotelid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hotelid");
                OnHotelidChanged();
            }
        }
        private global::System.Int32 _Hotelid;
        partial void OnHotelidChanging(global::System.Int32 value);
        partial void OnHotelidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PageCount
        {
            get
            {
                return _PageCount;
            }
            set
            {
                OnPageCountChanging(value);
                ReportPropertyChanging("PageCount");
                _PageCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PageCount");
                OnPageCountChanged();
            }
        }
        private global::System.Int32 _PageCount;
        partial void OnPageCountChanging(global::System.Int32 value);
        partial void OnPageCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShortContent
        {
            get
            {
                return _ShortContent;
            }
            set
            {
                OnShortContentChanging(value);
                ReportPropertyChanging("ShortContent");
                _ShortContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShortContent");
                OnShortContentChanged();
            }
        }
        private global::System.String _ShortContent;
        partial void OnShortContentChanging(global::System.String value);
        partial void OnShortContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> HotelRate
        {
            get
            {
                return _HotelRate;
            }
            set
            {
                OnHotelRateChanging(value);
                ReportPropertyChanging("HotelRate");
                _HotelRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HotelRate");
                OnHotelRateChanged();
            }
        }
        private Nullable<global::System.Single> _HotelRate;
        partial void OnHotelRateChanging(Nullable<global::System.Single> value);
        partial void OnHotelRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CommentDate
        {
            get
            {
                return _CommentDate;
            }
            set
            {
                OnCommentDateChanging(value);
                ReportPropertyChanging("CommentDate");
                _CommentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommentDate");
                OnCommentDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CommentDate;
        partial void OnCommentDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCommentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullContent
        {
            get
            {
                return _FullContent;
            }
            set
            {
                OnFullContentChanging(value);
                ReportPropertyChanging("FullContent");
                _FullContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullContent");
                OnFullContentChanged();
            }
        }
        private global::System.String _FullContent;
        partial void OnFullContentChanging(global::System.String value);
        partial void OnFullContentChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="global_dataModel", Name="hotelinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class hotelinfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new hotelinfo object.
        /// </summary>
        /// <param name="idHotelInfo">Initial value of the idHotelInfo property.</param>
        /// <param name="pageCount">Initial value of the PageCount property.</param>
        public static hotelinfo Createhotelinfo(global::System.Int32 idHotelInfo, global::System.Int32 pageCount)
        {
            hotelinfo hotelinfo = new hotelinfo();
            hotelinfo.idHotelInfo = idHotelInfo;
            hotelinfo.PageCount = pageCount;
            return hotelinfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idHotelInfo
        {
            get
            {
                return _idHotelInfo;
            }
            set
            {
                if (_idHotelInfo != value)
                {
                    OnidHotelInfoChanging(value);
                    ReportPropertyChanging("idHotelInfo");
                    _idHotelInfo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idHotelInfo");
                    OnidHotelInfoChanged();
                }
            }
        }
        private global::System.Int32 _idHotelInfo;
        partial void OnidHotelInfoChanging(global::System.Int32 value);
        partial void OnidHotelInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HotelName
        {
            get
            {
                return _HotelName;
            }
            set
            {
                OnHotelNameChanging(value);
                ReportPropertyChanging("HotelName");
                _HotelName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HotelName");
                OnHotelNameChanged();
            }
        }
        private global::System.String _HotelName;
        partial void OnHotelNameChanging(global::System.String value);
        partial void OnHotelNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HotelCity
        {
            get
            {
                return _HotelCity;
            }
            set
            {
                OnHotelCityChanging(value);
                ReportPropertyChanging("HotelCity");
                _HotelCity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HotelCity");
                OnHotelCityChanged();
            }
        }
        private global::System.String _HotelCity;
        partial void OnHotelCityChanging(global::System.String value);
        partial void OnHotelCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PageCount
        {
            get
            {
                return _PageCount;
            }
            set
            {
                OnPageCountChanging(value);
                ReportPropertyChanging("PageCount");
                _PageCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PageCount");
                OnPageCountChanged();
            }
        }
        private global::System.Int32 _PageCount;
        partial void OnPageCountChanging(global::System.Int32 value);
        partial void OnPageCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HotelDescription
        {
            get
            {
                return _HotelDescription;
            }
            set
            {
                OnHotelDescriptionChanging(value);
                ReportPropertyChanging("HotelDescription");
                _HotelDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HotelDescription");
                OnHotelDescriptionChanged();
            }
        }
        private global::System.String _HotelDescription;
        partial void OnHotelDescriptionChanging(global::System.String value);
        partial void OnHotelDescriptionChanged();

        #endregion

    
    }

    #endregion

    
}
